version: '3'

tasks:
  serve:
    desc: "Run hexerals on localhost:4200"
    cmds:
      - nx serve hexerals

  lint:
    desc: "Lint sourcecode; useful as a pre-commit hook"
    cmds:
      - nx run-many -t lint

  test:
    # TODO find a way to monitor tests while also serving; unfortunately "--watch" gets mangled with "--targets=test,serve"
    desc: "Monitor tests. To narrow tests, include '-- --testNamePattern <pattern>' or '-- --testFiles <pattern>'"
    cmds:
      # run-many is mighty: https://nx.dev/packages/nx/documents/run-many
      - nx run-many -t test {{.CLI_ARGS}} --watch

  migrate:
    desc: "Update nx tools and structure"
    cmds:
      - nx migrate latest